INSERT INTO equipment VALUES 
(default, 'kayak', 60, null), (default, 'kayak', 60, null),
(default, 'kayak', 60, null), (default, 'kayak', 60, null),
(default, 'kayak', 60, null), (default, 'kayak', 60, null),
(default, 'kayak', 60, null), (default, 'kayak', 60, null),
(default, 'kayak', 60, null), (default, 'kayak', 60, null),
(default, 'kayak', 60, null), (default, 'kayak', 60, null),
(default, 'kayak', 60, null), (default, 'kayak', 60, null),
(default, 'kayak', 60, null), (default, 'kayak', 60, null),
(default, 'kayak', 60, null), (default, 'kayak', 60, null),
(default, 'kayak', 60, null), (default, 'kayak', 60, null),

(default, 'helmet', 15, null), (default, 'helmet', 15, null),
(default, 'helmet', 15, null), (default, 'helmet', 15, null),
(default, 'helmet', 15, null), (default, 'helmet', 15, null),
(default, 'helmet', 15, null), (default, 'helmet', 15, null),
(default, 'helmet', 15, null), (default, 'helmet', 15, null),
(default, 'helmet', 15, null), (default, 'helmet', 15, null),
(default, 'helmet', 15, null), (default, 'helmet', 15, null),
(default, 'helmet', 15, null), (default, 'helmet', 15, null),
(default, 'helmet', 15, null), (default, 'helmet', 15, null),
(default, 'helmet', 15, null), (default, 'helmet', 15, null),

(default, 'BA', 30, null), (default, 'BA', 30, null),
(default, 'BA', 30, null), (default, 'BA', 30, null),
(default, 'BA', 30, null), (default, 'BA', 30, null),
(default, 'BA', 30, null), (default, 'BA', 30, null),
(default, 'BA', 30, null), (default, 'BA', 30, null),
(default, 'BA', 30, null), (default, 'BA', 30, null),
(default, 'BA', 30, null), (default, 'BA', 30, null),
(default, 'BA', 30, null), (default, 'BA', 30, null),
(default, 'BA', 30, null), (default, 'BA', 30, null),
(default, 'BA', 30, null), (default, 'BA', 30, null),

(default, 'paddle', 20, null), (default, 'paddle', 20, null),
(default, 'paddle', 20, null), (default, 'paddle', 20, null),
(default, 'paddle', 20, null), (default, 'paddle', 20, null),
(default, 'paddle', 20, null), (default, 'paddle', 20, null),
(default, 'paddle', 20, null), (default, 'paddle', 20, null),
(default, 'paddle', 20, null), (default, 'paddle', 20, null),
(default, 'paddle', 20, null), (default, 'paddle', 20, null),
(default, 'paddle', 20, null), (default, 'paddle', 60, null),
(default, 'paddle', 20, null), (default, 'paddle', 20, null),
(default, 'paddle', 20, null), (default, 'paddle', 20, null);



